/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.askcuix.push.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PushSysType implements org.apache.thrift.TEnum {
  MiPush(0),
  APNs(1);

  private final int value;

  private PushSysType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PushSysType findByValue(int value) { 
    switch (value) {
      case 0:
        return MiPush;
      case 1:
        return APNs;
      default:
        return null;
    }
  }
}
